"""Orpheus TTS model handler -- load and synthesize."""

import uuid
from io import BytesIO
from typing import Any

import numpy as np
import soundfile as sf

from tts_inference.types import VoiceConfig

MODEL_ID = "canopylabs/orpheus-3b-0.1-ft"
SAMPLE_RATE = 24000
DEFAULT_VOICE = "tara"


class OrpheusHandler:
    """Handler for Orpheus TTS."""

    def model_fn(self, model_dir: str) -> dict[str, Any]:
        from orpheus_tts import OrpheusModel

        model = OrpheusModel(model_name=model_dir or MODEL_ID, max_model_len=2048)
        return {"model": model}

    def predict_fn(
        self,
        text: str,
        model_artifacts: dict[str, Any],
        voice_config: VoiceConfig | None = None,
    ) -> tuple[bytes, int, float]:
        model = model_artifacts["model"]

        voice = DEFAULT_VOICE
        if voice_config and voice_config.voice_id:
            voice = voice_config.voice_id

        request_id = f"req-{uuid.uuid4().hex[:8]}"
        audio_chunks: list[bytes] = []
        for chunk in model.generate_speech(prompt=text, voice=voice, request_id=request_id):
            audio_chunks.append(chunk)

        if not audio_chunks:
            raise ValueError("No audio generated by model")

        raw_audio = b"".join(audio_chunks)
        audio_np = np.frombuffer(raw_audio, dtype=np.int16).astype(np.float32) / 32768.0
        duration = len(audio_np) / SAMPLE_RATE

        buffer = BytesIO()
        sf.write(buffer, audio_np, SAMPLE_RATE, format="WAV")
        wav_bytes = buffer.getvalue()

        return wav_bytes, SAMPLE_RATE, duration
