"""Maya1/Veena TTS model handler -- load and synthesize."""

from io import BytesIO
from typing import Any

import soundfile as sf
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

from tts_inference.types import VoiceConfig

MODEL_ID = "maya-research/veena-tts"
SNAC_MODEL_ID = "hubertsiuzdak/snac_24khz"
SAMPLE_RATE = 24000
DEFAULT_VOICE = "kavya"

START_OF_SPEECH_TOKEN = 128257
END_OF_SPEECH_TOKEN = 128258
START_OF_HUMAN_TOKEN = 128259
END_OF_HUMAN_TOKEN = 128260
START_OF_AI_TOKEN = 128261
END_OF_AI_TOKEN = 128262
AUDIO_CODE_BASE_OFFSET = 128266


def _decode_snac_tokens(snac_tokens: list[int], snac_model: Any) -> Any:
    """De-interleave and decode SNAC tokens to audio waveform."""
    if not snac_tokens or len(snac_tokens) % 7 != 0:
        raise ValueError(f"Invalid SNAC token count: {len(snac_tokens)} (must be divisible by 7)")

    snac_device = next(snac_model.parameters()).device
    llm_codebook_offsets = [AUDIO_CODE_BASE_OFFSET + i * 4096 for i in range(7)]

    codes_lvl: list[list[int]] = [[], [], []]
    for i in range(0, len(snac_tokens), 7):
        codes_lvl[0].append(snac_tokens[i] - llm_codebook_offsets[0])
        codes_lvl[1].append(snac_tokens[i + 1] - llm_codebook_offsets[1])
        codes_lvl[1].append(snac_tokens[i + 4] - llm_codebook_offsets[4])
        codes_lvl[2].append(snac_tokens[i + 2] - llm_codebook_offsets[2])
        codes_lvl[2].append(snac_tokens[i + 3] - llm_codebook_offsets[3])
        codes_lvl[2].append(snac_tokens[i + 5] - llm_codebook_offsets[5])
        codes_lvl[2].append(snac_tokens[i + 6] - llm_codebook_offsets[6])

    hierarchical_codes = []
    for lvl_codes in codes_lvl:
        tensor = torch.tensor(lvl_codes, dtype=torch.int32, device=snac_device).unsqueeze(0)
        if torch.any((tensor < 0) | (tensor > 4095)):
            raise ValueError("Invalid SNAC token values detected (out of codebook range)")
        hierarchical_codes.append(tensor)

    with torch.no_grad():
        audio_hat = snac_model.decode(hierarchical_codes)

    return audio_hat.squeeze().clamp(-1, 1).cpu().numpy()


class MayaHandler:
    """Handler for Maya1/Veena TTS."""

    def model_fn(self, model_dir: str) -> dict[str, Any]:
        from snac import SNAC

        quantization_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.bfloat16,
            bnb_4bit_use_double_quant=True,
        )

        model = AutoModelForCausalLM.from_pretrained(
            model_dir or MODEL_ID,
            quantization_config=quantization_config,
            device_map="auto",
            trust_remote_code=True,
        )

        tokenizer = AutoTokenizer.from_pretrained(
            model_dir or MODEL_ID,
            trust_remote_code=True,
        )

        snac_model = SNAC.from_pretrained(SNAC_MODEL_ID).eval().cuda()

        return {
            "model": model,
            "tokenizer": tokenizer,
            "snac_model": snac_model,
        }

    def predict_fn(
        self,
        text: str,
        model_artifacts: dict[str, Any],
        voice_config: VoiceConfig | None = None,
    ) -> tuple[bytes, int, float]:
        model = model_artifacts["model"]
        tokenizer = model_artifacts["tokenizer"]
        snac_model = model_artifacts["snac_model"]

        voice = DEFAULT_VOICE
        if voice_config and voice_config.voice_id:
            voice = voice_config.voice_id

        prompt = f"<spk_{voice}> {text}"
        prompt_tokens = tokenizer.encode(prompt, add_special_tokens=False)

        input_tokens = [
            START_OF_HUMAN_TOKEN,
            *prompt_tokens,
            END_OF_HUMAN_TOKEN,
            START_OF_AI_TOKEN,
            START_OF_SPEECH_TOKEN,
        ]

        input_ids = torch.tensor([input_tokens], device=model.device)
        max_tokens = min(int(len(text) * 1.3) * 7 + 21, 4096)

        with torch.no_grad():
            output = model.generate(
                input_ids,
                max_new_tokens=max_tokens,
                do_sample=True,
                temperature=0.4,
                top_p=0.9,
                repetition_penalty=1.05,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=[END_OF_SPEECH_TOKEN, END_OF_AI_TOKEN],
            )

        generated_ids = output[0][len(input_tokens) :].tolist()
        snac_tokens = [
            token_id
            for token_id in generated_ids
            if AUDIO_CODE_BASE_OFFSET <= token_id < (AUDIO_CODE_BASE_OFFSET + 7 * 4096)
        ]

        if not snac_tokens:
            raise ValueError("No audio tokens generated by the model")

        # Trim to multiple of 7
        snac_tokens = snac_tokens[: len(snac_tokens) // 7 * 7]

        audio_np = _decode_snac_tokens(snac_tokens, snac_model)
        duration = len(audio_np) / SAMPLE_RATE

        buffer = BytesIO()
        sf.write(buffer, audio_np, SAMPLE_RATE, format="WAV")
        wav_bytes = buffer.getvalue()

        return wav_bytes, SAMPLE_RATE, duration
